### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by pinrong** [Carinx/pc_wx_wxapkg_crack#2]
![image](https://user-images.githubusercontent.com/10151867/190852342-a4d6041a-64a2-45dc-a6ee-9e9909adc296.png)
第七步：删掉文件夹里面的文件

第八步：下载文件，然后把这个文件放入到文件夹中

文件下载下来后确保文件名跟下面一模一样：

WITHOUT_MULTI_PLUGINCODE.wxapkg

第九步：先关掉羊了个羊，再重新打开。
开始游戏，**-----错误发生在这里（重新开始游戏后报错如截图，并且重新加载后并无道具无限，似乎这个wxapkg被重新下载替换了） ps. 微信PC 版本号 3.7.6.44**

点右下角的（洗牌道具），看完广告，道具直接无限！

**Comment by Carinx** [comment]
> ![image](https://user-images.githubusercontent.com/10151867/190852342-a4d6041a-64a2-45dc-a6ee-9e9909adc296.png) 第七步：删掉文件夹里面的文件
> 
> 第八步：下载文件，然后把这个文件放入到文件夹中
> 
> 文件下载下来后确保文件名跟下面一模一样：
> 
> WITHOUT_MULTI_PLUGINCODE.wxapkg
> 
> 第九步：先关掉羊了个羊，再重新打开。 开始游戏，**-----错误发生在这里（重新开始游戏后报错如截图，并且重新加载后并无道具无限，似乎这个wxapkg被重新下载替换了） ps. 微信PC 版本号 3.7.6.44**
> 
> 点右下角的（洗牌道具），看完广告，道具直接无限！

你截图呢？看不到耶，不过俺的版本应该比你的低一点好好😂

**Comment by pinrong** [comment]
呀，截图在前面看不到吗？
其实就是微信小程序报错：加载小程序代码包失败，请尝试清除本地缓存后重新打开小程序。
点关闭按钮后自动重新加载（似乎是加载了官方最新代码包并替换掉了刚刚patched的代码包）

**Comment by Carinx** [comment]
> 

我刚试了官方的最新版本3.7确实是不可以，不过我的3.5是ok的，你可以试一下3.7以下的版本，谢谢你的提醒啦是😂

**Comment by Carinx** [comment]
> 呀，截图在前面看不到吗？ 其实就是微信小程序报错：加载小程序代码包失败，请尝试清除本地缓存后重新打开小程序。 点关闭按钮后自动重新加载（似乎是加载了官方最新代码包并替换掉了刚刚patched的代码包）

我刚试了官方的最新版本3.7确实是不可以，不过我的3.5是ok的，你可以试一下3.7以下的版本，谢谢你的提醒啦是😂

**Comment by pinrong** [comment]
> > 呀，截图在前面看不到吗？ 其实就是微信小程序报错：加载小程序代码包失败，请尝试清除本地缓存后重新打开小程序。 点关闭按钮后自动重新加载（似乎是加载了官方最新代码包并替换掉了刚刚patched的代码包）
> 
> 我刚试了官方的最新版本3.7确实是不可以，不过我的3.5是ok的，你可以试一下3.7以下的版本，谢谢你的提醒啦是😂

不客气，果然改用3.5就可以！
